name: RSS to JSON
on:
  schedule:
    - cron: "0 * * * *"     # Runs every hour
  workflow_dispatch:
jobs:
  rss2json:
    name: read RSS and convert into one json
    runs-on: ubuntu-latest
    steps:
      - uses: I-Valchev/rss-to-json@1.0.0
        with:
          source: feeds.yaml # An optional parameter to specify the source. Defaults to feeds.yaml
          target: feeds.json # An optional parameter to specify the target. Defaults to feeds.json
          sortBy: isoDate
          sortOrder: desc
