name: RSS to MD
on:
  schedule:
    - cron: "0 * * * *"     # Runs every hour
  workflow_dispatch:
jobs:
  rss2md:
    name:  RSS to MD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sarisia/actions-readme-feed@v1
        with:
          file: 'README.md'
          timezone: 'Asia/taipei'
          max_entry: 100
          url: |
            https://wenchiehlee.wordpress.com/feed
            https://wenchiehlee.github.io/feed.xml
            https://www.google.com/alerts/feeds/12063940936216578696/8793798168837785642
            https://www.google.com/alerts/feeds/12063940936216578696/8793798168837786674
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: verify README
      #    path: README.md
      #    if: always()
      - if: ${{ steps.feed.outputs.changed == true }}
        uses: sarisia/actions-commit@master
